name: Deploy NLLB Translation Service

on:
  workflow_run:
    workflows: ["LoRA_Training_Workflow"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Trained Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model-lora
          path: ./models/custom-nllb

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t onkar-nllb-translation:latest .

      - name: Push Docker Image
        run: |
          docker push onkar-nllb-translation:latest

      - name: Deploy (optional)
        run: |
          echo "Add kubectl / SSH deploy here"